name: Bug report
description: Report a reproducible problem in AgentWatch
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please provide enough detail to reproduce it.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened vs what you expected
      placeholder: Brief description of the bug
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Include exact steps and values where possible
      placeholder: |
        1. Open app
        2. Go to settings
        3. Click ...
        4. See error
    validations:
      required: true
  - type: input
    id: app_version
    attributes:
      label: AgentWatch version
      placeholder: e.g. 1.3.0
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: e.g. Windows 11 23H2
    validations:
      required: true
  - type: input
    id: node
    attributes:
      label: Node version (if running from source)
      placeholder: e.g. v20.11.1
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs/errors
      description: Paste sanitized logs only. Do not include cookies/tokens.
      render: shell
  - type: textarea
    id: extra
    attributes:
      label: Additional context
      description: Screenshots, recordings, or anything else helpful
